# 端口号
PORT: 10000

# 日志
# 0，打开日志
# 1，关闭日志
close_log: 0

# 日志写入方式，默认同步
# 0，同步写入
# 1，异步写入
LOGWrite: 1

# 日志等级，LOG_DEBUG: 0, LOG_INFO: 1, LOG_WARN: 2, LOG_ERROR: 3
# 显示大于等于LogLevel的
LogLevel: 1

# 触发组合模式,默认listenfd LT + connfd LT
# 0，表示使用LT + LT
# 1，表示使用LT + ET
# 2，表示使用ET + LT
# 3，表示使用ET + ET
TriggerMode: 0

# 优雅关闭链接，默认不使用
# 0，不使用
# 1，使用
OPT_LINGER: 0

# 数据库连接池数量,默认8
sql_num: 8

# 线程池内的线程数量,默认8
thread_num: 8


# 并发模型,默认是proactor
# 0，Proactor模型
# 1，Reactor模型
actor_model: 0




# 数据库相关参数
databaseParameter:

  # 登录用户名
  user: "chen"

  # 登录密码
  passwd: "12345678"

  # 数据库名称
  databasename: "webserver"