# chenWeb 配置文件

# 端口号
Port: 10000

# listen_fd + conn_fd
# 0，表示使用LT + LT
# 1，表示使用LT + ET
# 2，表示使用ET + LT
# 3，表示使用ET + ET
TriggerMode: 3

# 线程池内的线程数量
ThreadNum: 10

# 任务请求队列最大数量
MaxRequests: 10000

# 优雅关闭链接
# 0，不使用
# 1，使用
ElegantCloseLinger: 0

# 并发模型
# 0，Proactor模型
# 1，Reactor模型 , 暂不支持
ActorModel: 0

# 日志相关
Log:
  # 0，关闭日志
  # 1，打开日志
  LogIsOpen: 0

  # 0，日志同步写入
  # 1，日志异步写入
  LogWriteWay: 0

  # 日志等级，LOG_DEBUG: 0, LOG_INFO: 1, LOG_WARN: 2, LOG_ERROR: 3
  # 显示大于等于LogLevel的
  LogLevel: 0

  # 日志文件保存位置
  LogFilePath: "./bin/log/chenWebLog"



# 数据库相关参数
DatabaseParameter:
  # 数据库地址
  SqlHost: "localhost"

  # 数据库端口
  SqlPort: 3306

  # 登录用户名
  User: "chen"

  # 登录密码
  PassWord: "12345678"

  # 数据库名称
  DatabaseName: "webserver"

  # 数据库连接池线程数量
  SqlThreadNum: 8
