name: sync2gitee
on:
  push:
  # schedule:
    # 定时计划
    #- cron:  '0 1 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get current repository name
      id: info
      uses: actions/github-script@v3.1
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        result-encoding: string
        script: |
            return context.repo.repo;
            
    - name: Mirror the Github organization repos to Gitee.
      uses: Yikun/hub-mirror-action@master
      with:

        src: github/chenanga
        dst: gitee/ang-chen
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        dst_token:  ${{ secrets.GITEE_TOKEN }}
        # mappings: '${{ steps.info.outputs.result }}=>myweb'   # 映射
        static_list: '${{ steps.info.outputs.result }}'
        account_type: user
        force_update: true
